export const [READ_LATER, CURRENTLY_READING, FINISHED] = ["Read later", "Currently reading", "Finished"];
export const [UNFINISHED_TO_FINISHED, FINISHED_TO_UNFINISHED, UNFINISHED_TO_UNFINISHED] = [
  "UNFINISHED_TO_FINISHED",
  "FINISHED_TO_UNFINISHED",
  "UNFINISHED_TO_UNFINISHED",
];
